// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbQhd7CrYxV-zkETXFLuNYq2HhRu9AXQo',
    appId: '1:852635784115:android:f1b09f8a30fb5729bfb1c6',
    messagingSenderId: '852635784115',
    projectId: 'najottalim-aa473',
    databaseURL: 'https://najottalim-aa473-default-rtdb.firebaseio.com',
    storageBucket: 'najottalim-aa473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3n83UbJeNOIhmIHwOcURB9NoHwYkex0',
    appId: '1:852635784115:ios:e33a6779883bda66bfb1c6',
    messagingSenderId: '852635784115',
    projectId: 'najottalim-aa473',
    databaseURL: 'https://najottalim-aa473-default-rtdb.firebaseio.com',
    storageBucket: 'najottalim-aa473.appspot.com',
    iosClientId: '852635784115-pfei2i727hsa60a109gfnapmbp01cig5.apps.googleusercontent.com',
    iosBundleId: 'com.ultrainha.najottalim',
  );
}
